### ISSUE TITLE
Can process only the first worksheet

### ISSUE THREAD

**Issue by boychev** [LibreCat/Catmandu-XLS#15]
The XLS importer only allows processing the first worksheet. Could you add an optional parameter to specify which worksheet to process?

**Comment by jorol** [comment]
Thanks for the comment. I will add that in the next release.

**Comment by boychev** [comment]
Thank you!

**Comment by jorol** [comment]
Just pushed v.0.07 to CPAN.

You can now adress a specific worksheet by its index (0,1,2,...). Default 0.

```terminal
catmandu convert XLS --worksheet 1 --file ./t/test.xls to JSON
```
