### ISSUE TITLE
XLSX importer ignores the formatting rules of columns

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu-XLS#5]
E.g. in Excel a date can be formatted as '01/01/90' which results in a number 32874 when imported into Catmandu.

**Comment by jorol** [comment]
Can you send a test file to rolschewski@gmail.com?

**Comment by jorol** [comment]
It's a bug in Spreadsheet::XLSX, see https://rt.cpan.org/Public/Bug/Display.html?id=87746.

**Comment by jorol** [comment]
Solved for XLS importer in #6.

**Comment by jorol** [comment]
Switched from Spreadsheet::XLSX to Spreadsheet::ParseXLSX. Fixed in v0.08.
